primary:
  spring:
    datasource:
      jdbc-url: jdbc:mysql://localhost:3306/test
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 920725
secondary:
  spring:
    datasource:
      jdbc-url: jdbc:mysql://localhost:3306/testdb
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 920725
#spring:
#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration,org.mybatis.spring.boot.autoconfigure.MybatisAutoConfiguration